services:
  - type: web
    name: zeon-xmtp-agent
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    # Only deploy when backend files change (ignore frontend changes)
    ignoredPaths:
      - "frontend/**"
      - "frontend/*"
      - "**/frontend/**"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: XMTP_ENV
        value: dev
      - key: WALLET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: CDP_API_KEY_NAME
        sync: false
      - key: CDP_API_KEY_PRIVATE_KEY
        sync: false
      - key: NETWORK_ID
        value: base-sepolia
      - key: OPENROUTER_API_KEY
        sync: false