services:
  - type: web
    name: zeon-hybrid-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CDP_API_KEY_NAME
        sync: false
      - key: CDP_API_KEY_PRIVATE_KEY
        sync: false
      - key: NETWORK_ID
        value: base-sepolia
      - key: OPENROUTER_API_KEY
        sync: false